name: Java CI Master

on:
  push:
    branches: [master]

jobs:
  test:
    name: GradleTest
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      - name: Test
        run: ./gradlew test --tests "*"

      - name: Test Success
        if: success()
        with:
          script: |
            echo -e "\n### Hurray passed the basic Gradle test ###\n"
      - name: Test Failed
        if: success()
        with:
          script: |
            echo -e "\n### Dohhh! Did not pass the basic Gradle test ###\n"




   
